version: "3"
services:

  fv-backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      fv-db:
        condition: service_healthy

  fv-db:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: "my_example"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
